spring.datasource.url=jdbc:postgresql://localhost:5432/scannerdb
spring.datasource.username=postgres
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger y H2
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
