server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: scan-service
          uri: http://scan-service:8082
          predicates:
            - Path=/scan/**
          filters:
            - StripPrefix=1
        - id: report-service
          uri: http://report-service:8084
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1
        - id: client-info-service
          uri: http://client-info-service:8083
          predicates:
            - Path=/client-info/**
      default-filters:
        - AddResponseHeader=X-Api-Gateway, cybersecurity-project

cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true